apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta
  labels:
    app: meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta
  template:
    metadata:
      labels:
        app: meta
    spec:
      containers:
        - image: phanikumarps/meta:latest #change it to your image
          imagePullPolicy: Always
          name: meta
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: meta
  labels:
    app: meta
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: meta
